### ISSUE TITLE
Assertion error at terms/rba_buffer_terms.c:151 (mcsat)

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#340] opened 2020-12-05 13:47 UTC
Hi, for the following formula
[151.txt](https://github.com/SRI-CSL/yices2/files/5647157/151.txt)

yices2 --incremental --mcsat 258b902

~~~~
yices_smt2: terms/rba_buffer_terms.c:151: rba_buffer_add_const_times_term: Assertion `pos_term(t) && good_term(table, t) && is_arithmetic_term(table, t)' failed.
~~~~

**Comment by dddejan** [comment] 2020-12-08 15:27
duplicate of #338

**Closed by dddejan** 2020-12-08 15:27 UTC
