### ISSUE TITLE
Assertion violation at mcsat/solver.c:1496

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#215] opened 2020-05-09 03:03 UTC
~~~~
(set-logic QF_NRA)
(declare-fun _substvar_190_ () Real)
(declare-fun _substvar_198_ () Bool)
(declare-const r0 Real)
(declare-const r2 Real)
(declare-const r3 Real)
(declare-const r5 Real)
(declare-const r6 Real)
(declare-const r8 Real)
(declare-const r10 Real)
(assert (= (+ 15351.13 r2 (* 8347837.0 8347837.0 r3) r3 r3) (* r3 (* 15351.13 (+ r3 (+ 15351.13 r2 (* 8347837.0 8347837.0 r3) r3 r3) 740.8 (* r8 r5 r6 r3 r0)) r2 19983.0 (* r8 r5 r6 r3 r0)) r0 r5 15351.13) 19983.0 _substvar_190_ r10))
(assert (or (distinct (/ (+ r3 (+ 15351.13 r2 (* 8347837.0 8347837.0 r3) r3 r3) 740.8 r6) (* r8 r5 r6 r3 r0)) 0.0 15351.13 r5 r8) _substvar_198_))
(check-sat)
~~~~

yices commit 36f29beb9
~~~~
yices_smt2: mcsat/solver.c:1496: mcsat_add_lemma: Assertion `trail_get_value(mcsat->trail, disjunct_pos_var)->b == (disjunct != disjunct_pos)' failed.
~~~~

**Comment by dddejan** [comment] 2020-05-09 14:29
Cannot reproduce, this seems to be a duplicate of #203. That one was a bug in LibPoly that was fixed.  

@rainoftime Can you try updating LibPoly to the latest version and try again.

**Closed** 2020-05-12 14:59 UTC
Labels: QF_NRA, duplicate, mcsat
