### ISSUE TITLE
Assertion error at  mcsat/preprocessor.c:82 (mcsat)

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#339] opened 2020-12-05 13:20 UTC
Hi, for the following formula

[82.txt](https://github.com/SRI-CSL/yices2/files/5647117/82.txt)

yices2 --incremental --mcsat 258b902
~~~~
unsat
unsat
yices_smt2: mcsat/preprocessor.c:82: preprocessor_set: Assertion `preprocessor_get(pre, t) == (-1)' failed.
~~~~

**Comment by dddejan** [comment] 2020-12-08 15:25
duplicate of #338

**Closed by dddejan** 2020-12-08 15:25 UTC
