### ISSUE TITLE
Invalid model for LIA formula

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#328] opened 2020-10-18 05:00 UTC
Hi, for this formula, yices 7139142
givens an invalid model
[lia_invalid.txt](https://github.com/SRI-CSL/yices2/files/5397073/lia_invalid.txt)
[lia_invalid_with_model.txt](https://github.com/SRI-CSL/yices2/files/5397074/lia_invalid_with_model.txt)

When feeding the model to yices and cvc4, the solvers decide the formula is unsat.

**Comment by dddejan** [comment] 2020-10-28 14:30
This seems to be duplicate of #329, should be checked when fixed.

**Closed by dddejan** 2020-10-28 14:30 UTC
Labels: bug, quantifiers
