### ISSUE TITLE
Assertion violation at libpoly/src/utils/assignment.c:122

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#279] opened 2020-07-30 10:15 UTC
yices2 e51be0d

~~~~
(set-logic QF_UFNRA)
(declare-const r0 Real)
(declare-const r2 Real)
(declare-const r3 Real)
(declare-const r4 Real)
(declare-const r5 Real)
(declare-const r6 Real)
(declare-const r7 Real)
(declare-const r8 Real)
(declare-const r9 Real)
(declare-const r10 Real)
(declare-const v23 Bool)
(declare-const r11 Real)
(declare-const r12 Real)
(declare-const r13 Real)
(declare-const v27 Bool)
(declare-const r14 Real)
(declare-const r15 Real)
(declare-const r16 Real)
(declare-const r17 Real)
(declare-const r18 Real)
(assert (or v27 (> r10 (/ (+ (/ (- (- 40.0 40.0 r0 1.0)) (- r0)) 40.0 (/ (- 40.0 40.0 r0 1.0) r4) r3) (/ (- r0) 1.0)) (/ (* (- (- 40.0 40.0 r0 1.0)) 1.0 40.0) (- 40.0 40.0 r0 1.0)))))
(assert (or (<= r2 68814788.0) (> r10 (/ (+ (/ (- (- 40.0 40.0 r0 1.0)) (- r0)) 40.0 (/ (- 40.0 40.0 r0 1.0) r4) r3) (/ (- r0) 1.0)) (/ (* (- (- 40.0 40.0 r0 1.0)) 1.0 40.0) (- 40.0 40.0 r0 1.0))) (> r10 (/ (+ (/ (- (- 40.0 40.0 r0 1.0)) (- r0)) 40.0 (/ (- 40.0 40.0 r0 1.0) r4) r3) (/ (- r0) 1.0)) (/ (* (- (- 40.0 40.0 r0 1.0)) 1.0 40.0) (- 40.0 40.0 r0 1.0))) (<= r2 68814788.0)))
(assert (or v23 v27 (<= r2 68814788.0) v27 (<= r2 68814788.0) v23 v23))
(assert (or (<= r2 68814788.0) v23 (<= r2 68814788.0)))
(assert (or v23 (<= r2 68814788.0) (> r10 (/ (+ (/ (- (- 40.0 40.0 r0 1.0)) (- r0)) 40.0 (/ (- 40.0 40.0 r0 1.0) r4) r3) (/ (- r0) 1.0)) (/ (* (- (- 40.0 40.0 r0 1.0)) 1.0 40.0) (- 40.0 40.0 r0 1.0)))))
(assert (or (> r10 (/ (+ (/ (- (- 40.0 40.0 r0 1.0)) (- r0)) 40.0 (/ (- 40.0 40.0 r0 1.0) r4) r3) (/ (- r0) 1.0)) (/ (* (- (- 40.0 40.0 r0 1.0)) 1.0 40.0) (- 40.0 40.0 r0 1.0))) v23 (> r10 (/ (+ (/ (- (- 40.0 40.0 r0 1.0)) (- r0)) 40.0 (/ (- 40.0 40.0 r0 1.0) r4) r3) (/ (- r0) 1.0)) (/ (* (- (- 40.0 40.0 r0 1.0)) 1.0 40.0) (- 40.0 40.0 r0 1.0))) (<= r2 68814788.0) v27 (> r10 (/ (+ (/ (- (- 40.0 40.0 r0 1.0)) (- r0)) 40.0 (/ (- 40.0 40.0 r0 1.0) r4) r3) (/ (- r0) 1.0)) (/ (* (- (- 40.0 40.0 r0 1.0)) 1.0 40.0) (- 40.0 40.0 r0 1.0))) (<= r2 68814788.0) (> r10 (/ (+ (/ (- (- 40.0 40.0 r0 1.0)) (- r0)) 40.0 (/ (- 40.0 40.0 r0 1.0) r4) r3) (/ (- r0) 1.0)) (/ (* (- (- 40.0 40.0 r0 1.0)) 1.0 40.0) (- 40.0 40.0 r0 1.0)))))
(assert (or (<= r2 68814788.0) v27 (<= r2 68814788.0) v27))
(assert (or v27 v23))
(assert (or (> r10 (/ (+ (/ (- (- 40.0 40.0 r0 1.0)) (- r0)) 40.0 (/ (- 40.0 40.0 r0 1.0) r4) r3) (/ (- r0) 1.0)) (/ (* (- (- 40.0 40.0 r0 1.0)) 1.0 40.0) (- 40.0 40.0 r0 1.0))) (> r10 (/ (+ (/ (- (- 40.0 40.0 r0 1.0)) (- r0)) 40.0 (/ (- 40.0 40.0 r0 1.0) r4) r3) (/ (- r0) 1.0)) (/ (* (- (- 40.0 40.0 r0 1.0)) 1.0 40.0) (- 40.0 40.0 r0 1.0)))))
(check-sat-assuming-model (r0 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 r13 r14 r15 r16 r17 r18 ) (6056.0 3.0 55023131.0 0.40 2932.0 4187.0 1.0 93477.0 8260.0 0.3 498.0 82.57896726 0.3011384397 0.1213451690 0.9523 493520.0 448756683.0 1457766.0 ))
~~~~

~~~~
yices_smt2: /home/libpoly/src/utils/assignment.c:122: lp_assignment_get_value_approx: Assertion `lp_assignment_get_value(m, x)->type != LP_VALUE_NONE' failed.
~~~~

**Comment by dddejan** [comment] 2020-07-31 14:06
This is using `check-sat-assuming-model` which is not available in the the provided commit. In the latest on `mcsat-assumptions` branch the example doesn't fail. Closing since I cannot reproduce. Please reopen if you can find a commit where it fails.

**Closed by dddejan** 2020-07-31 14:06 UTC
Labels: experimental, interpolation, invalid
