### ISSUE TITLE
Refutation soundness issue on quantified formulas

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#327] opened 2020-10-17 11:25 UTC
Hi, for the following formula,
yices db1923a yield `unsat`
but both z3 and cvc4 return `sat`.
~~~~
(set-logic LIA)
(declare-fun _substvar_249_ () Bool)
(declare-const v20 Bool)
(assert (xor true true true true _substvar_249_ true v20 (forall ((q20 Bool) (q21 Bool) (q22 Int) (q23 Int) (q24 Bool) (q25 Bool)) (distinct q23 2971))))
(check-sat)
~~~~

**Comment by rainoftime** [comment] 2020-10-17 11:28
A LRA formula
~~~~
(set-logic LRA)
(declare-fun _substvar_514_ () Bool)
(assert (not (forall ((q89 Real) (q90 Bool) (q91 Bool) (q92 Bool) (q93 Bool)) (xor true true (exists ((q10 Real) (q11 Bool) (q12 Bool) (q13 Bool) (q14 Real)) q13) true true _substvar_514_ q91 true))))
(check-sat)
~~~~

**Comment by rainoftime** [comment] 2020-10-17 11:31
A UF formula
~~~~
(set-logic UF)
(declare-fun _substvar_449_ () Bool)
(declare-fun _substvar_844_ () Bool)
(assert (xor true _substvar_449_ true true true _substvar_844_ true (exists ((q23 Bool)) q23)))
(check-sat)
~~~~

**Comment by rainoftime** [comment] 2020-10-17 13:45
~~~~
(set-logic BV)
(declare-fun _substvar_238_ () Bool)
(declare-fun _substvar_280_ () Bool)
(assert (xor true true _substvar_238_ _substvar_280_ (exists ((q9 (_ BitVec 8)) (q10 (_ BitVec 8)) (q11 (_ BitVec 6))) (bvult (_ bv0 6) q11)) true true))
(check-sat)
~~~~

**Comment by dddejan** [comment] 2020-10-28 14:36
simplified example

```smt2 
(set-logic LIA)

(declare-const x Bool)
(declare-const y Bool)

(assert
  (xor
   x y true
   (forall ((z Int)) (= z 0))
  )
)

(check-sat)
```

Seems duplicate of #328, should be checked there.

**Closed by dddejan** 2020-10-28 14:36 UTC
Labels: bug, quantifiers
