### ISSUE TITLE
Assertion violation at mcsat/nra/nra_plugin_explain.c:661

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#204] opened 2020-04-30 12:30 UTC
Hi, for the following formula,
[yice.txt](https://github.com/SRI-CSL/yices2/files/4558281/yice.txt)

yices2 (commit afb9bfd) throws an assertion violation
~~~~
Value is false (should be true)
var = 373
yices_smt2: mcsat/nra/nra_plugin_explain.c:661: lp_projection_map_construct_cell: Assertion `ensure_true(ctx, ub_root_atom)' failed.
~~~~

**Comment by dddejan** [comment] 2020-04-30 14:57
Duplicate of #203

**Closed by dddejan** 2020-04-30 14:57 UTC
Labels: duplicate
