### ISSUE TITLE
Assertion error at model/concrete_values.h:906 (show-implicant)

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#323] opened 2020-10-13 12:22 UTC
Hi, for this formula, yices 25fada8
~~~~
$ cat xx.ys
(define r2::real)
(define bool3::bool)
(define r4::real)
(define r3::real)
(define bool4::bool)
(define bool21::bool)
(define r1::real)
(define bool1::bool)
(define r7::real)
(assert (or (= (distinct r4 r3) bool3) (= (distinct r4 r3) bool3) false))
(assert (and (not (= bool21 (not bool1))) (not (distinct 248.0 (* (/ r2 9781306209.0) r7 r4 (+ r2 r4 248.0 r2) r7)))))
(assert (or (xor (not bool1) (not bool1)) bool4 (<= (- 480.0) (- (* r2 r1 r2))) false))
(check)
(show-implicant)

$ ./yices  --mode=one-shot --mcsat xx.ys
sat
yices: ./model/concrete_values.h:906: vtbl_rational: Assertion `object_is_rational(table, v)' failed.
~~~~

**Comment by dddejan** [comment] 2020-10-13 14:02
Issue with algebraic number computations.

**Comment by dddejan** [comment] 2020-10-13 14:12
Duplicate of #321

**Closed by dddejan** 2020-10-13 14:12 UTC
Labels: mcsat
